### ISSUE TITLE
Android 13 上有问题 打开就闪退

### ISSUE THREAD

**Issue by hyk12345** [cairuoyu/flutter_admin#27]
Flutter com.example.flutter_admin: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

**Comment by hyk12345** [comment]
java.lang.IllegalArgumentException: com.example.flutter_admin: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:404)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:674)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:661)
	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by cairuoyu** [comment]
已修复
